@startuml diagramToCode
skinparam ClassAttributeIconSize 0
hide circle

class Person {
  - name: string
  
  + Person(name: string)
  + print(): void
  + setName(name: string): void
  + getName(): string
}

@enduml